// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRasX49D7WRXkYSVgzSvLN4CJM_pgsxyg',
    appId: '1:682206727646:web:082b90e79ec99b8a16214f',
    messagingSenderId: '682206727646',
    projectId: 'chick-chack-97c32',
    authDomain: 'chick-chack-97c32.firebaseapp.com',
    databaseURL: 'https://chick-chack-97c32-default-rtdb.firebaseio.com',
    storageBucket: 'chick-chack-97c32.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0mOB-c4MIiF6iMndQCTu6M7A8hT1tLtA',
    appId: '1:682206727646:android:7174b29ad39778fc16214f',
    messagingSenderId: '682206727646',
    projectId: 'chick-chack-97c32',
    databaseURL: 'https://chick-chack-97c32-default-rtdb.firebaseio.com',
    storageBucket: 'chick-chack-97c32.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB67EN9rduu8faz2QqzAZCKkyxYwbaDtiw',
    appId: '1:682206727646:ios:95f3a66c6ad99a9c16214f',
    messagingSenderId: '682206727646',
    projectId: 'chick-chack-97c32',
    databaseURL: 'https://chick-chack-97c32-default-rtdb.firebaseio.com',
    storageBucket: 'chick-chack-97c32.appspot.com',
    iosBundleId: 'com.example.chickChackBeta',
  );
}
